INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('book', 12.49, 'BOOK');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('music CD', 14.99, 'OTHER');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('chocolate bar', 0.85, 'FOOD');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('imported box of chocolates', 10.00, 'FOOD');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('imported bottle of perfume', 47.50, 'OTHER');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('imported bottle of perfume', 27.99, 'OTHER');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('bottle of perfume', 18.99, 'OTHER');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('packet of headache pills', 9.75, 'MEDICAL PRODUCT');
INSERT INTO ITEMS (ITEM_NAME,ITEM_PRICE,ITEM_CATEGORY) VALUES ('box of imported chocolates', 11.25, 'FOOD');