-- INIT SERVER TABLE
INSERT INTO SERVER(NAME, DESCRIPTION) VALUES ('server1', 'Machine 1');
INSERT INTO SERVER(NAME, DESCRIPTION) VALUES ('server2', 'Machine 2');
INSERT INTO SERVER(NAME, DESCRIPTION) VALUES ('server3', 'Machine 3');
INSERT INTO SERVER(NAME, DESCRIPTION) VALUES ('server4', 'Machine 4');